# Generated by Django 5.0.2 on 2024-02-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('cv', models.TextField()),
                ('picture', models.ImageField(upload_to='cleaner_pictures/')),
                ('work_experience', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
