# Generated by Django 4.2.1 on 2024-03-02 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleaners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleaners.cleaner')),
            ],
        ),
    ]
